Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,7 +3,9 @@ on:
   schedule:
     - cron: '*/5 * * * *'  # Runs every 5 minutes
   workflow_dispatch:  # Allows manual triggering
-
+permissions:
+  contents: write
+  
 jobs:
   update-json:
     runs-on: ubuntu-latest
@@ -13,7 +15,10 @@ jobs:
 
       - name: Fetch JSON data
         run: |
-          curl -s https://test.devseventeam.workers.dev/matches -o matches.json
+          curl -s https://raw.githubusercontent.com/devxseven/mmfot-data/refs/heads/main/main.json -o matches.json || {
+            echo "Error: Failed to fetch JSON from URL" >&2
+            exit 1
+          }
 
       - name: Update JSON file in repository
         uses: test-room-7/action-update-file@v1
